// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8vo8mJAGy2hQhqHvIZ3Asa3lXon7gdKo',
    appId: '1:612349312110:web:9935c90a95018bf1a5ba7f',
    messagingSenderId: '612349312110',
    projectId: 'z-fans',
    authDomain: 'z-fans.firebaseapp.com',
    storageBucket: 'z-fans.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiwSpTU-t_wZUzWe97Si0Uf_q4wiRFR6A',
    appId: '1:612349312110:android:37747959c15fbbf5a5ba7f',
    messagingSenderId: '612349312110',
    projectId: 'z-fans',
    storageBucket: 'z-fans.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5F3VJxTqY3zJG0gUNgx6j1VUN9B25sg0',
    appId: '1:612349312110:ios:e41c54ba52b82056a5ba7f',
    messagingSenderId: '612349312110',
    projectId: 'z-fans',
    storageBucket: 'z-fans.appspot.com',
    iosBundleId: 'com.example.zamalekFansApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5F3VJxTqY3zJG0gUNgx6j1VUN9B25sg0',
    appId: '1:612349312110:ios:034476e9dd51ffe3a5ba7f',
    messagingSenderId: '612349312110',
    projectId: 'z-fans',
    storageBucket: 'z-fans.appspot.com',
    iosBundleId: 'z',
  );
}
